AWSTemplateFormatVersion: '2010-09-09'

Description: Deploys the stellar/quickstart docker image (ephemeral mode, testnet) in a Public VPC with a single availibility zone.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Instance"
        Parameters: [InstanceType, InstanceKeyPair]
      - Label:
          default: "Access"
        Parameters: [SshIpRange, HorizonIpRange, HorizonPort]

    ParameterLabels:
      InstanceType:
        default: "Instance Type"
      InstanceKeyPair:
        default: "Key Pair"
      SshIpRange:
        default: "IP Range for SSH Access"
      HorizonIpRange:
        default: "IP Range for Horizon Access"
      HorizonPort:
        default: "Horizon Port"

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, m4.large, m5.large, c4.large, c5.large]
    ConstraintDescription: Please choose a valid instance type.

  InstanceKeyPair:
    Description: EC2 key pair used to SSH into the instance
    Type: AWS::EC2::KeyPair::KeyName
    MinLength: 1 # Force check for value before deployment

  SshIpRange:
    Description: IP range (CIDR notation) that will be allowed to SSH into the instance. Use https://www.google.com/search?q=ip to find you IP and enter it as x.x.x.x/32.
    Type: String
    AllowedPattern: "^([0-9]+\\.){3}[0-9]+/[0-9]{1,2}$"
    ConstraintDescription: "Must be a valid IP CIDR range of the form x.x.x.x/x."
    MinLength: 9
    Default: 123.456.789.0/32

  HorizonIpRange:
    Description: IP range (CIDR notation) that will be allowed to access the Horizon. Leave blank to block all external access
    Type: String
    AllowedPattern: "^(([0-9]+\\.){3}[0-9]+/[0-9]{1,2})*$"
    ConstraintDescription: "Must be a valid IP CIDR range of the form x.x.x.x/x."

  HorizonPort:
    Description: EC2 Instance port for Horizon (access may still be restricted by IP)
    Type: Number
    Default: 8000


Conditions:
  AllowHorizonAccess: !Not [!Equals [ !Ref HorizonIpRange, '' ]]

Mappings:
  # Latest ECS optimized AMIs as of Apr 02 2018:
  # amzn-ami-2017.09.k-amazon-ecs-optimized. ECS agent: 1.17.2, Docker: 17.12.0-ce, ecs-init: 1.17.2-1
  # You can find the latest available images here: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
  AwsRegionMap:
    ap-northeast-1:
      AMI: ami-5add893c
    ap-northeast-2:
      AMI: ami-ba74d8d4
    ap-south-1:
      AMI: ami-2149114e
    ap-southeast-1:
      AMI: ami-acbcefd0
    ap-southeast-2:
      AMI: ami-4cc5072e
    ca-central-1:
      AMI: ami-a535b2c1
    eu-central-1:
      AMI: ami-ac055447
    eu-west-1:
      AMI: ami-bfb5fec6
    eu-west-2:
      AMI: ami-a48d6bc3
    eu-west-3:
      AMI: ami-914afcec
    sa-east-1:
      AMI: ami-d3bce9bf
    us-east-1:
      AMI: ami-cb17d8b6
    us-east-2:
      AMI: ami-1b90a67e
    us-west-1:
      AMI: ami-9cbbaffc
    us-west-2:
      AMI: ami-05b5277d

  CustomParamsMap:
    Get:
      DbPort: 5432

  # These are all soft limits so they are not enforced or representative of per container usage
  # These memory limits are effectively just being used to reserve the full capacity of the EC2 instance for the service
  # A specific amount is reserved by each instance type for system usage. The full advertised amount is not available.
  # You have to log into and instance and run "free -m" to determine what is available to that instance type.
  # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/memory-management.html
  MemoryReservationMap:
    t2.nano:
      quickstart: 480
    t2.micro:
      quickstart: 990
    t2.small:
      quickstart: 1990
    t2.medium:
      quickstart: 3945
    t2.large:
      quickstart: 7980
    m4.large:
      quickstart: 7980
    m5.large:
      quickstart: 7680
    c4.large:
      quickstart: 3760
    c5.large:
      quickstart: 3705

Resources:
  # Network
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: '10.200.0.0/16'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref 'Vpc'
      CidrBlock: '10.200.0.0/24'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'

  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'Vpc'
      InternetGatewayId: !Ref 'InternetGateway'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'Vpc'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachement
    Properties:
      RouteTableId: !Ref 'PublicRouteTable'
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # ECS Resources
  EcsCluster:
    Type: AWS::ECS::Cluster

  EcsHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref AWS::StackName
      GroupDescription: Access to the ECS hosts that run containers
      VpcId: !Ref 'Vpc'
      SecurityGroupIngress:
        - CidrIp: !Ref SshIpRange
          Description: Allow SSH access via a specific IP Range
          IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'

  # Specify this here instead of above so that we can use the "Condition" key
  EcsSecurityGroupIngressHorizon:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: AllowHorizonAccess
    Properties:
      GroupId: !Ref 'EcsHostSecurityGroup'
      Description: Allow Horizon access via a specific IP Range
      CidrIp: !Ref HorizonIpRange
      IpProtocol: 'tcp'
      FromPort: !Ref 'HorizonPort'
      ToPort: !Ref 'HorizonPort'

  EcsSecurityGroupIngressFromSelf:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'EcsHostSecurityGroup'
      Description: Ingress from other hosts in the same security group
      IpProtocol: -1
      SourceSecurityGroupId: !Ref 'EcsHostSecurityGroup'

  # This launches the actual EC2 instance that will register as a member of the cluster and run the containers.
  EcsAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnet
      LaunchConfigurationName: !Ref 'EcsLaunchConfiguration'
      MinSize: 1
      MaxSize: 2 # Allows capacity for AutoScalingReplacingUpdate
      DesiredCapacity: 1
      MetricsCollection:
        - Granularity: '1Minute'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
          PropagateAtLaunch: 'true'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'

  EcsInstanceElasticIP:
    Type: AWS::EC2::EIP
    DependsOn: GatewayAttachement # Associating the IP with the vpc requires that we add this dependency explicitly
    Properties:
      Domain: vpc

  EcsLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [AwsRegionMap, !Ref 'AWS::Region', AMI]
      SecurityGroups: [!Ref 'EcsHostSecurityGroup']
      InstanceType: !Ref 'InstanceType'
      IamInstanceProfile: !Ref 'Ec2InstanceProfile'
      InstanceMonitoring: false # Disable detailed monitoring at the instance level to avoid additional charges. ECS provides detailed CPU data
      KeyName: !Ref 'InstanceKeyPair'
      AssociatePublicIpAddress: 'true' # Will be replaced by elastic IP, but we need a public ip at the start to install packages
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash

            ##### INSTALL UPDATES AND TOOLS
            yum update -y --security
            yum install -y aws-cli aws-cfn-bootstrap awslogs jq

            ##### ASSIGN ELASTIC IP
            # Get the instance id from instance metadata and assign the elastic ip to this instance
            instance_id=$(curl http://169.254.169.254/latest/meta-data/instance-id)
            aws ec2 associate-address --instance-id $instance_id --allocation-id ${EcsInstanceElasticIP.AllocationId} --region ${AWS::Region}

            ##### SETUP INSTANCE LOGS
            # Set the region to send CloudWatch Logs data to the region where the container instance is located
            sed -i -e "s/region = us-east-1/region = ${AWS::Region}/g" /etc/awslogs/awscli.conf

            # Inject the CloudWatch Logs configuration file contents
            cat > /etc/awslogs/awslogs.conf <<- EOF
            [general]
            state_file = /var/lib/awslogs/agent-state

            [/var/log/messages]
            file = /var/log/messages
            log_group_name = ${instancesLogGroup}
            log_stream_name = {container_instance_id}/var/log/messages
            datetime_format = %b %d %H:%M:%S

            [/var/log/cfn-init.log]
            file = /var/log/cfn-init.log
            log_group_name = ${instancesLogGroup}
            log_stream_name = {container_instance_id}/var/log/cfn-init.log
            datetime_format = %Y-%m-%dT%H:%M:%SZ

            [/var/log/cloud-init-output.log]
            file = /var/log/cloud-init-output.log
            log_group_name = ${instancesLogGroup}
            log_stream_name = {container_instance_id}/var/log/cloud-init-output.log
            datetime_format = %Y-%m-%dT%H:%M:%SZ
            EOF

            # Get the instance id from instance metadata and replace the container instance ID placeholders with the actual values
            container_instance_id=$(curl http://169.254.169.254/latest/meta-data/instance-id)
            sed -i -e "s/{container_instance_id}/$container_instance_id/g" /etc/awslogs/awslogs.conf

            # Start/Enable awslogs service
            service awslogs start
            chkconfig awslogs on

            ##### ECS CLUSTER CONFIG
            # Update the cluster config with the cluster name
            echo ECS_CLUSTER=${EcsCluster} >> /etc/ecs/ecs.config

            ##### SIGNAL ASG
            # Send a signal to the AutoScalingGroup with the return value of the last command to let it know creation completed
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EcsAutoScalingGroup --region ${AWS::Region}
          - instancesLogGroup: !Sub '/stellar/${AWS::StackName}-instances' # hardcoded in outputs also

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref 'Ec2Role']

  # Role for the EC2 hosts. This allows the ECS agent on the EC2 hosts to communicate with the ECS control plane.
  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role']
      Policies: # Additional permissions beyond AmazonEC2ContainerServiceforEC2Role used for instance logging
        - PolicyName: 'AllowInstanceLogs'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [ 'logs:CreateLogGroup', 'logs:DescribeLogStreams' ]
                Resource: 'arn:aws:logs:*:*:*'
        - PolicyName: 'AssociateElasticIP'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [ 'ec2:AllocateAddress', 'ec2:AssociateAddress', 'ec2:DescribeAddresses', 'ec2:DisassociateAddress' ]
                Resource: '*'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: ['ec2.amazonaws.com']
          Action: ['sts:AssumeRole']

  EcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 100 # Shutdown the old task before starting the new one, don't want the writing to efs/db simultaneously
        MinimumHealthyPercent: 0
      TaskDefinition: !Ref EcsTaskDefinition

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref 'AWS::StackName'
      ContainerDefinitions:
        - Name: 'quickstart'
          Essential: true
          Image: stellar/quickstart
          Command: ["--testnet"]
          MemoryReservation: !FindInMap [MemoryReservationMap, !Ref 'InstanceType', quickstart]
          Environment:
            - Name: 'POSTGRES_PASSWORD'
              Value: !GetAtt DatabasePassword.Password
          PortMappings:
            - ContainerPort: 8000
              HostPort: !Ref 'HorizonPort'
            - ContainerPort: !FindInMap [CustomParamsMap, Get, DbPort]
              HostPort: !FindInMap [CustomParamsMap, Get, DbPort]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'ContainersLogGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'AWS::StackName'

  DatabasePassword:
    Type: 'AWS::CloudFormation::CustomResource'
    Properties:
      ServiceToken: !GetAtt PasswordGeneratorLambda.Arn
      ParameterNamePrefix: !Sub '/${AWS::StackName}/database/master-password'

  PasswordGeneratorLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: 'Generates random password'
      Handler: 'index.handler'
      Role: !GetAtt PasswordGeneratorRole.Arn
      Code:
        ZipFile: |
          const response = require('cfn-response');
          const AWS = require('aws-sdk');
          const ssm = new AWS.SSM();

          exports.handler = (event, context) => {
            if (event.RequestType == 'Delete') {
              // Remove param when CloudFormation deletes the resource. The param name is the PhysicalResourceId
              ssm.deleteParameter({ Name: event.PhysicalResourceId }).promise()
                .then((data) => {
                  return response.send(event, context, response.SUCCESS, data);
              }).catch((err)=> {
                  return response.send(event, context, response.FAILED, err);
              });
            }
            else{ // Create or Update. Update (only happens when param name changes) will return a new physical id which will cause CF to delete the old one
              let responseData;

              new BackportedSecretsManager().getRandomPassword({ PasswordLength: 45, ExcludePunctuation: true }).promise()
                .then((data) => {
                  const password = data.RandomPassword.substring(0, 32); // We only really wanted 32 chars for the password
                  const randomString = data.RandomPassword.substring(32); // Last 13 used to add randomness to the SSM param name to avoid deletion on replacement
                  const paramName = event.ResourceProperties.ParameterNamePrefix + '-' + randomString;

                  responseData = {
                    ParameterName: paramName,
                    EncodedParameterName: encodeURIComponent(encodeURIComponent(paramName)), // Double encoded to work with AWS console
                    Password: password
                  }

                  const params = {
                    Name: paramName,
                    Type: 'SecureString',
                    Value: password,
                    Overwrite: true
                  };
                  return ssm.putParameter(params).promise();
              }).then(() => {
                  return response.send(event, context, response.SUCCESS, responseData, responseData.ParameterName); // Use param name as PhysicalResourceId
              }).catch((err)=> {
                  return response.send(event, context, response.FAILED, err);
              });
            }
          };

          // The Nodejs SDK currently available to Lambda doesn't yet support the Secrets Manager API
          // This is the code from latest sdk required to support a minimal version of getRandomPassword() only

          const BackportedSecretsManager = AWS.Service.defineService('secretsmanager', ['2017-10-17']);
          AWS.apiLoader.services['secretsmanager'] = {};
          Object.defineProperty(AWS.apiLoader.services['secretsmanager'], '2017-10-17', {
            get: function get() { return secretsmanagerModel; }, enumerable: true, configurable: true
          });

          const secretsmanagerModel = {
            version: '2.0',
            metadata: {
              apiVersion: '2017-10-17',
              endpointPrefix: 'secretsmanager',
              jsonVersion: '1.1',
              protocol: 'json',
              serviceFullName: 'AWS Secrets Manager',
              serviceId: 'Secrets Manager',
              signatureVersion: 'v4',
              signingName: 'secretsmanager',
              targetPrefix: 'secretsmanager',
              uid: 'secretsmanager-2017-10-17'
            },
            operations: {
              GetRandomPassword: {
                input: { type: 'structure', members: { PasswordLength: { type: 'long' }, ExcludePunctuation: { type: 'boolean' } } },
                output: { type: 'structure', members: { RandomPassword: {} } }
              }
            }
          };
      Runtime: 'nodejs6.10'
      Timeout: '30'

  PasswordGeneratorRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: '/'
      ManagedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole']
      Policies:
        - PolicyName: 'GeneratePassword'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'secretsmanager:GetRandomPassword'
                Resource: '*'
        - PolicyName: 'CreateSsmParams'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['ssm:PutParameter', 'ssm:DeleteParameter', 'kms:Encrypt']
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'

  ContainersLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/stellar/${AWS::StackName}-containers'
      RetentionInDays: 7

Outputs:
  SshUrl:
    Value: !Sub 'ssh://ec2-user@${EcsInstanceElasticIP}'
  HorizonUrl:
    Condition: AllowHorizonAccess
    Value: !Sub 'http://${EcsInstanceElasticIP}:${HorizonPort}'
  ContainersLogGroup:
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${ContainersLogGroup}'
  InstancesLogGroup:
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=/stellar/${AWS::StackName}-instances'
  AutoScalingGroup:
    Value: !Sub 'https://console.aws.amazon.com/ec2/autoscaling/home?region=${AWS::Region}#AutoScalingGroups:id=${EcsAutoScalingGroup};view=instances'
  ECS:
    Value: !Sub 'https://console.aws.amazon.com/ecs/home?region=${AWS::Region}#/clusters/${EcsCluster}/services/${EcsService.Name}/events'
  DatabaseUsername:
    Value: 'stellar' # Currently hardcoded in https://github.com/stellar/docker-stellar-core-horizon/blob/master/start
  DatabasePassword:
    Value: !Sub 'https://console.aws.amazon.com/systems-manager/parameters/${DatabasePassword.EncodedParameterName}/description?region=${AWS::Region}'